
[breeder]
	#The time in ticks the breeder takes to create a new villager
	#Range: > 20
	breeding_time = 240

[converter]
	#The time in ticks the converter takes to convert a villager
	#Range: > 20
	converting_time = 80

[farmer]
	#Lower values mean faster growth
	#Range: > 1
	farm_speed = 80

[iron_farm]
	#The time in ticks the iron farm takes to spawn a golem
	#Range: > 201
	spawn_time = 4800

[trader]
	#The minimum amount of time in ticks the trader takes to restock
	#Range: > 1
	min_restock_time = 240
	#The maximum amount of time in ticks the trader takes to restock
	#Range: > 2
	max_restock_time = 720

[villager]
	#If villagers should make sounds while in the players inventory
	inventory_sounds = false

